spring:
  application:
    name: "code-review"

app:
  github:
    app:
      app-id: ${APP_ID}
      private-key: ${APP_PEM}
    webhook:
      secret-key: ${WEBHOOK_SECRET}
    api:
      token: ${API_TOKEN_GITHUB}
  google:
    api-key: ${GEMINI_API_KEY}
